{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "y5widmw3lnhovcilvihypugamm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 247025,
          "sha512": "48388533d69f968565ac8aff9e077afb346f305926bd7874a06fa2c076e3cee8cb09d4861a0ec5accc70ca9eaab9487010013c15a5f6a7394b48d3bcad2ac420",
          "sha256": "f55d2051c0300da8f6000d8df64bb8a3bb4c33412edbe5c95753755ab6dd8fb2",
          "sha1": "d3baca03e1f4651bc50da34dd14a90a3774bddbe",
          "md5": "ae0b8d034e2f40095718cbec12ae60cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.4.6+build.74"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.3.0.70"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.2.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "2.0.0+build.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz-io-proguard",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "procyon-fabric-compilertools",
          "version": {
            "requires": "0.5.35.13"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "intellij-fernflower",
          "version": {
            "requires": "1.2.1.16"
          }
        },
        {
          "group": "org.benf",
          "module": "cfr",
          "version": {
            "requires": "0.150"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "mercury",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 247025,
          "sha512": "48388533d69f968565ac8aff9e077afb346f305926bd7874a06fa2c076e3cee8cb09d4861a0ec5accc70ca9eaab9487010013c15a5f6a7394b48d3bcad2ac420",
          "sha256": "f55d2051c0300da8f6000d8df64bb8a3bb4c33412edbe5c95753755ab6dd8fb2",
          "sha1": "d3baca03e1f4651bc50da34dd14a90a3774bddbe",
          "md5": "ae0b8d034e2f40095718cbec12ae60cd"
        }
      ]
    }
  ]
}
