{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "lx4atlxyxfcohaa2q5t2srwzte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246689,
          "sha512": "11599de52ec4e887956dfcdb5c5899c19b604338a45e24279a071c437d121e68cab24a01341d013dd28416f309da7552906bcdf1a40dc67bbbb0493a9b103692",
          "sha256": "c854ff88bc2d52dee643dd87f91d0b559aa164db9e8dd1cf5dcd088183b95c57",
          "sha1": "cf9f81471eb19142353383f869b6199c55e741f1",
          "md5": "e766b7aeb4f47d69fefd2f3b865a57c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.4.6+build.74"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.3.0.70"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.2.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "2.0.0+build.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz-io-proguard",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "procyon-fabric-compilertools",
          "version": {
            "requires": "0.5.35.13"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "intellij-fernflower",
          "version": {
            "requires": "1.2.1.16"
          }
        },
        {
          "group": "org.benf",
          "module": "cfr",
          "version": {
            "requires": "0.150"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "mercury",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246689,
          "sha512": "11599de52ec4e887956dfcdb5c5899c19b604338a45e24279a071c437d121e68cab24a01341d013dd28416f309da7552906bcdf1a40dc67bbbb0493a9b103692",
          "sha256": "c854ff88bc2d52dee643dd87f91d0b559aa164db9e8dd1cf5dcd088183b95c57",
          "sha1": "cf9f81471eb19142353383f869b6199c55e741f1",
          "md5": "e766b7aeb4f47d69fefd2f3b865a57c4"
        }
      ]
    }
  ]
}
