{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "epf2tz4o7rddlmjtmc52erylxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246698,
          "sha512": "f36522a0d189a3d0d0388c904e77676ce2e1e01e49a2d82d108ca13304e5322ac0d633f21d323e44353148e9cf14df13ef4a22bf728d95c4a225368b7483943e",
          "sha256": "56fb7779eb4ac90c485df4d24d22457380b304f5e8e2fecfe0b6c5c19cfcd94d",
          "sha1": "b9203f4a9c173d9fa920452f8d79cf35adbf056e",
          "md5": "f9c70efece8efda5aad84880c2a2286d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.4.6+build.74"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.3.0.70"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.2.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "2.0.0+build.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz-io-proguard",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "procyon-fabric-compilertools",
          "version": {
            "requires": "0.5.35.13"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "intellij-fernflower",
          "version": {
            "requires": "1.2.1.16"
          }
        },
        {
          "group": "org.benf",
          "module": "cfr",
          "version": {
            "requires": "0.150"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "mercury",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246698,
          "sha512": "f36522a0d189a3d0d0388c904e77676ce2e1e01e49a2d82d108ca13304e5322ac0d633f21d323e44353148e9cf14df13ef4a22bf728d95c4a225368b7483943e",
          "sha256": "56fb7779eb4ac90c485df4d24d22457380b304f5e8e2fecfe0b6c5c19cfcd94d",
          "sha1": "b9203f4a9c173d9fa920452f8d79cf35adbf056e",
          "md5": "f9c70efece8efda5aad84880c2a2286d"
        }
      ]
    }
  ]
}
