{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "atmfp2ftljedtiktj3digigncq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246924,
          "sha512": "3549d7b3c7ee9b3966ee172b671a417aede6a0e942ee52111622d87eb4b944ffb353298c01bbc46d173ba206826cf6ae9189b9e32700c4c9a50fa97d3b1262ae",
          "sha256": "b9a19f405b8682da60d25988c278081df8c0a94cf615c962a0fa8f1d09b955e1",
          "sha1": "aadcf26d899346a62e05bf2b98a1f1dc17aa11f8",
          "md5": "550c0d456eb985b32e2e72ffc1b0cfa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.4.6+build.74"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.3.0.70"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.2.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "2.0.0+build.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz-io-proguard",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "procyon-fabric-compilertools",
          "version": {
            "requires": "0.5.35.13"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "intellij-fernflower",
          "version": {
            "requires": "1.2.1.16"
          }
        },
        {
          "group": "org.benf",
          "module": "cfr",
          "version": {
            "requires": "0.150"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "mercury",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246924,
          "sha512": "3549d7b3c7ee9b3966ee172b671a417aede6a0e942ee52111622d87eb4b944ffb353298c01bbc46d173ba206826cf6ae9189b9e32700c4c9a50fa97d3b1262ae",
          "sha256": "b9a19f405b8682da60d25988c278081df8c0a94cf615c962a0fa8f1d09b955e1",
          "sha1": "aadcf26d899346a62e05bf2b98a1f1dc17aa11f8",
          "md5": "550c0d456eb985b32e2e72ffc1b0cfa8"
        }
      ]
    }
  ]
}
