{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "7ehdatveqfbljdajamgph56koy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246686,
          "sha512": "0ac738533db287448558c90b957ddfff6e4a858156370daf70a66669ba64880264315403c893942e9ecd8cbdd72262f708ac094ada7a7d4ac10a8e88846c20eb",
          "sha256": "72fea4a1a6a3240d9d586db42dd554f92414619bb80eed46ab3dc7eb4438ab46",
          "sha1": "d57382fbf665d73b24c458c465336d0cbad57ffa",
          "md5": "9e0f56b3ce2458484c52ae3dd572304d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.zeroturnaround",
          "module": "zt-zip",
          "version": {
            "requires": "1.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.4.6+build.74"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.3.0.70"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.2.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "2.0.0+build.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz-io-proguard",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "procyon-fabric-compilertools",
          "version": {
            "requires": "0.5.35.13"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "intellij-fernflower",
          "version": {
            "requires": "1.2.1.16"
          }
        },
        {
          "group": "org.benf",
          "module": "cfr",
          "version": {
            "requires": "0.150"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "mercury",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-loom-0.5-SNAPSHOT.jar",
          "url": "fabric-loom-0.5-SNAPSHOT.jar",
          "size": 246686,
          "sha512": "0ac738533db287448558c90b957ddfff6e4a858156370daf70a66669ba64880264315403c893942e9ecd8cbdd72262f708ac094ada7a7d4ac10a8e88846c20eb",
          "sha256": "72fea4a1a6a3240d9d586db42dd554f92414619bb80eed46ab3dc7eb4438ab46",
          "sha1": "d57382fbf665d73b24c458c465336d0cbad57ffa",
          "md5": "9e0f56b3ce2458484c52ae3dd572304d"
        }
      ]
    }
  ]
}
